---
# tasks file for install Vagrant on Linux system

- name: Linux | Find all versions of Vagrant
  uri:
    url: https://releases.hashicorp.com/vagrant/index.json
    return_content: yes
  register: vagrant_index
  check_mode: no
  when: vagrant_version == 'latest'

- name: Linux | Finds the latest version of Vagrant when latest var is define
  set_fact:
    vagrant_version_to_install: "{{ (vagrant_index.content | from_json).versions | list | sort_versions | last }}"
  when: vagrant_version == 'latest'

- name: Linux | Use the specified Vagrant version when latest var is not define
  set_fact:
    vagrant_version_to_install: "{{ vagrant_version }}"
  when: vagrant_version != 'latest'

# This task avoids downloading Vagrant every time
- name: Linux | Check if Vagrant is present with the right version
  command: vagrant --version
  register: vagrant_installed_version
  ignore_errors: yes
  changed_when: false
  failed_when: false

- name: yum | Install Vagrant
  yum:
    name: "https://releases.hashicorp.com/vagrant/{{ vagrant_version_to_install }}/vagrant_{{ vagrant_version_to_install }}_x86_64.rpm"
    disable_gpg_check: yes
    allow_downgrade: yes
    state: present
  when:
    - ansible_pkg_mgr == "yum"
    - vagrant_version_to_install not in vagrant_installed_version.stdout | default('')

- name: dnf | Install Vagrant
  dnf:
    name: "https://releases.hashicorp.com/vagrant/{{ vagrant_version_to_install }}/vagrant_{{ vagrant_version_to_install }}_x86_64.rpm"
    disable_gpg_check: yes # https://github.com/aws/amazon-ssm-agent/issues/235
    state: present
  when:
    - ansible_pkg_mgr == "dnf"
    - vagrant_version_to_install not in vagrant_installed_version.stdout | default('')

- name: zypper | Install Vagrant
  zypper:
    name: "https://releases.hashicorp.com/vagrant/{{ vagrant_version_to_install }}/vagrant_{{ vagrant_version_to_install }}_x86_64.rpm"
    disable_gpg_check: yes
    force: yes
    state: present
  when:
    - ansible_pkg_mgr == "zypper"
    - vagrant_version_to_install not in vagrant_installed_version.stdout | default('')

# Downgrade vagrant package cannot be performed because ansible module apt
# do not support package downgrade safely https://github.com/ansible/ansible/pull/33677
- name: apt | Install Vagrant
  apt:
    deb: "https://releases.hashicorp.com/vagrant/{{ vagrant_version_to_install }}/vagrant_{{ vagrant_version_to_install }}_x86_64.deb"
    state: present
  when:
    - ansible_pkg_mgr == "apt"
    - vagrant_version_to_install not in vagrant_installed_version.stdout | default('')

- name: Linux | Install Vagrant with Hashicorp generic package
  unarchive:
    src: "https://releases.hashicorp.com/vagrant/{{ vagrant_version_to_install }}/vagrant_{{ vagrant_version_to_install }}_linux_amd64.zip"
    dest: "{{ vagrant_path }}"
    mode: '0755'
    remote_src: yes
  when:
    - ansible_pkg_mgr != "dnf"
    - ansible_pkg_mgr != "yum"
    - ansible_pkg_mgr != "zypper"
    - ansible_pkg_mgr != "apt"
    - vagrant_version_to_install not in vagrant_installed_version.stdout | default('')
